# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f genome-annotation-conda.yml
name: genome-annotation
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - repeatmasker=4.0.7 
 - exonerate=2.4.0 
 - blast=2.5.0 
 - perl-bioperl=1.6.924  
 - genometools-genometools=1.5.10 
