# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f genome-annotation-conda.yml
name: genome-annotation-1.0
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - parallel
 - samtools=1.9
 - repeatmasker=4.0.7
 - cdbtools
 - exonerate=2.4.0 
 - genometools-genometools=1.5.10 
 - trinity=2.8.4
 - fastqc=0.11.7
 - fastp=0.19.5
 - augustus=3.2.3
 - hisat2=2.1.0
 - multiqc=1.6
