genome: ""
proteins: false
ESTs: false
rm_lib: false
rm_species: mammals
reads: false
trinity: false
training: false
training_models: 1000
pasa: false
augustus: true
model: "human"
augCfg: false
evm: false
nevm: 10
uniprot: false
chunk_size: 50000
nblast: 200
blast_evalue: 0.001
nexonerate: 100
nchunks: 20
singleEnd: false
rnaseq_stranded: false
max_intron_size: 100000
email: false
