genome: ""
proteins: ""
ESTs: ""
rm_lib: false
rm_species: false
reads: ""
trinity: false
training: false
training_models: 1000
pasa: false
augustus: false
model: "human"
augCfg: false
uniprot: false
nblast: 200
blast_evalue: 0.001
nexonerate: 100
nrepeats: 20
singleEnd: false
rnaseq_stranded: false
outdir: "output"
run_name: "evidences"
max_intron_size: 100000
email: false
