genome: ""
proteins: ""
ESTs: ""
rm_lib: ""
rm_species: "mammal"
reads: ""
trinity: false
gth: false
augustus: false
model: "human"
UTR: "off"
isof: false
augCfg: false
uniprot: false
nblast: 200
blast_evalue: 0.001
nexonerate: 100
nrepeats: 20
singleEnd: false
rnaseq_stranded: false
outdir: "output"
run_name: "evidences"
max_intron_size: 100000
email: false
